name: generate-sitemap

on:
  push:
    branches: [ seo ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: generate-sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://project4.myportfolio.training
        include-pdf: false
        sitemap-format: xml

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
